# Generated by Django 3.1.1 on 2020-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=12)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalzip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
